<?php

return [
    'boot' => [
         'System\\App\\UtilCache\\Configs\\Boot',
         'System\\App\\UtilDataTable\\Configs\\Boot',
         'System\\App\\UtilDateTime\\Configs\\Boot',
         'System\\App\\UtilFileSystem\\Configs\\Boot',
         'System\\App\\UtilFirebase\\Configs\\Boot',
         'System\\App\\UtilLang\\Configs\\Boot',
         'System\\App\\UtilModel\\Configs\\Boot',
         'System\\App\\UtilORM\\Configs\\Boot',
         'System\\App\\UtilRequest\\Configs\\Boot',
         'System\\App\\UtilResponse\\Configs\\Boot',
         'System\\App\\UtilSecurity\\Configs\\Boot',
         'System\\App\\UtilSession\\Configs\\Boot',
         'System\\App\\UtilString\\Configs\\Boot',
         'System\\App\\UtilView\\Configs\\Boot',
         'App\\Components\\Main\\Configs\\Boot',
         'App\\Components\\AdminAuth\\Configs\\Boot',
    ],
    'middleware' => [
         'System\\App\\UtilCache\\Configs\\Middleware',
         'System\\App\\UtilDataTable\\Configs\\Middleware',
         'System\\App\\UtilDateTime\\Configs\\Middleware',
         'System\\App\\UtilFileSystem\\Configs\\Middleware',
         'System\\App\\UtilFirebase\\Configs\\Middleware',
         'System\\App\\UtilLang\\Configs\\Middleware',
         'System\\App\\UtilModel\\Configs\\Middleware',
         'System\\App\\UtilORM\\Configs\\Middleware',
         'System\\App\\UtilRequest\\Configs\\Middleware',
         'System\\App\\UtilResponse\\Configs\\Middleware',
         'System\\App\\UtilSecurity\\Configs\\Middleware',
         'System\\App\\UtilSession\\Configs\\Middleware',
         'System\\App\\UtilString\\Configs\\Middleware',
         'System\\App\\UtilView\\Configs\\Middleware',
         'App\\Components\\Main\\Configs\\Middleware',
         'App\\Components\\AdminAuth\\Configs\\Middleware',
    ],
    'route' => [
        'admin/auth/login' => [
             'App\\Components\\AdminAuth\\Controllers\\AdminAuthController',
             'login',
        ],
        '/' => [
             'App\\Components\\Main\\Controllers\\HomeController',
             'index',
        ],
    ],
    'helper' => [
         'System\\App\\UtilCache\\Configs\\Helper',
         'System\\App\\UtilDataTable\\Configs\\Helper',
         'System\\App\\UtilDateTime\\Configs\\Helper',
         'System\\App\\UtilFileSystem\\Configs\\Helper',
         'System\\App\\UtilFirebase\\Configs\\Helper',
         'System\\App\\UtilLang\\Configs\\Helper',
         'System\\App\\UtilModel\\Configs\\Helper',
         'System\\App\\UtilORM\\Configs\\Helper',
         'System\\App\\UtilRequest\\Configs\\Helper',
         'System\\App\\UtilResponse\\Configs\\Helper',
         'System\\App\\UtilSecurity\\Configs\\Helper',
         'System\\App\\UtilSession\\Configs\\Helper',
         'System\\App\\UtilString\\Configs\\Helper',
         'System\\App\\UtilView\\Configs\\Helper',
         'App\\Components\\Main\\Configs\\Helper',
         'App\\Components\\AdminAuth\\Configs\\Helper',
    ],
    'command' => [
         'System\\App\\UtilModel\\Configs\\Command',
    ],
];