#!/usr/bin/env php
<?php require_once "vendor/autoload.php";

/**
 * We want to know where this project run
 */
define("BASE_PATH", getcwd());
define("BASE_DIR", dirname(__FILE__));

echo "SUPER FRAMEWORK CLI TOOL\n";
echo "=================================\n";

(new \System\Super())->commandRun($argv);