#!/usr/bin/env php
<?php use System\Commands\CommandRunner;

require_once "vendor/autoload.php";

/**
 * We want to know where this project run
 */
define("BASE_PATH", getcwd());
define("BASE_DIR", dirname(__FILE__));

(new CommandRunner())->run($argv);