<?php

return [
    'admin' => 'App\\Modules\\Admin\\Controllers\\AdminController@index',
    'admin/index' => 'App\\Modules\\Admin\\Controllers\\AdminController@index',
    'admin-api/auth' => 'App\\Modules\\AdminAPI\\Controllers\\ApiAuthController@index',
    'admin-api/auth/login' => 'App\\Modules\\AdminAPI\\Controllers\\ApiAuthController@login',
    'admin-api/auth/check-session' => 'App\\Modules\\AdminAPI\\Controllers\\ApiAuthController@checkSession',
    'admin-api/auth/logout' => 'App\\Modules\\AdminAPI\\Controllers\\ApiAuthController@logout',
    'admin-api/authors' => 'App\\Modules\\AdminAPI\\Controllers\\ApiAuthorsController@index',
    'admin-api/authors/list' => 'App\\Modules\\AdminAPI\\Controllers\\ApiAuthorsController@list',
    'admin-api/authors/create' => 'App\\Modules\\AdminAPI\\Controllers\\ApiAuthorsController@create',
    'admin-api/authors/read' => 'App\\Modules\\AdminAPI\\Controllers\\ApiAuthorsController@read',
    'admin-api/authors/update' => 'App\\Modules\\AdminAPI\\Controllers\\ApiAuthorsController@update',
    'admin-api/authors/delete' => 'App\\Modules\\AdminAPI\\Controllers\\ApiAuthorsController@delete',
    'admin-api/books' => 'App\\Modules\\AdminAPI\\Controllers\\ApiBooksController@index',
    'admin-api/books/list' => 'App\\Modules\\AdminAPI\\Controllers\\ApiBooksController@list',
    'admin-api/books/create' => 'App\\Modules\\AdminAPI\\Controllers\\ApiBooksController@create',
    'admin-api/books/read' => 'App\\Modules\\AdminAPI\\Controllers\\ApiBooksController@read',
    'admin-api/books/update' => 'App\\Modules\\AdminAPI\\Controllers\\ApiBooksController@update',
    'admin-api/books/delete' => 'App\\Modules\\AdminAPI\\Controllers\\ApiBooksController@delete',
    'admin-api/users' => 'App\\Modules\\AdminAPI\\Controllers\\ApiUsersController@index',
    'admin-api/users/update-profile' => 'App\\Modules\\AdminAPI\\Controllers\\ApiUsersController@updateProfile',
    'home' => 'App\\Modules\\Site\\Controllers\\Home@index',
    'home/index' => 'App\\Modules\\Site\\Controllers\\Home@index',
];